package com.tuan.chatserver.enums;

public enum EventType {
    MESSAGE_NEW,
    MESSAGE_STATUS_UPDATED_TO_RECEIVED,
    MESSAGE_STATUS_UPDATED_TO_SEEN,
    MESSAGE_RECALLED,
    GROUP_CHAT_CREATED,
    GROUP_RENAMED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_LEFT,
    ADDED_TO_GROUP,
    REMOVED_FROM_GROUP,
    ROLE_CHANGED,
    PRESENCE_ONLINE,
    PRESENCE_OFFLINE,
    ADMIN_USER_STATS_UPDATED,
    ADMIN_CHATBOX_STATS_UPDATED,
    ADMIN_MESSAGE_STATS_UPDATED,
    ADMIN_REGISTERED,
    USER_ACTIVE_STATUS_CHANGED,
    ADMIN_USER_ONLINE,
    ADMIN_USER_OFFLINE
}